services:
  - type: web
    name: evento-backend
    region: oregon
    plan: free
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: evento
      - key: JWT_SECRET
        generateValue: true
      - key: BREVO_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: Evento
      - key: REPLY_TO_EMAIL
        sync: false
  - type: web
    name: evento-frontend
    runtime: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
